name: Get current ENV_VAR Date
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: version  # this is used on variable path
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.version.outputs.builddate }}
          RELEASE_NAME: nightly-release-${{ steps.version.outputs.builddate }}
