name: Get current ENV_VAR Date
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: builddate  # this is used on variable path
        run: |
          WeekDay=$(date +%w)
          LastFriday=$(date +'%Y%m%d' -d "$((WeekDay+2)) day ago")
          PrevFriday=$(date +'%Y%m%d' -d "$((WeekDay+9)) day ago") 
          if [[ $WeekDay -lt 4 ]]; then DateRef=$PrevFriday; else DateRef=$LastFriday; fi
          echo "dateref=$DateRef" >> $GITHUB_OUTPUT        
        
      - name: Test with environment variables
        run: echo ${{ steps.builddate.outputs.dateref }}
