name: Flat

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 4'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # This step build variable "DateRef" to assign URL and FILENAME source!
      - name: Build DateRef
        id: builddate  # this is used on variable path
        run: |
          WeekDay=$(date +%w)
          LastFriday=$(date +'%Y%m%d' -d "$((WeekDay+2)) day ago")
          PrevFriday=$(date +'%Y%m%d' -d "$((WeekDay+9)) day ago") 
          if [[ $WeekDay -lt 4 ]]; then DateRef=$PrevFriday; else DateRef=$LastFriday; fi
          echo "dateref=$DateRef" >> $GITHUB_OUTPUT
      # This step installs Deno, which is a new Javascript runtime that improves on Node. Can be used for an optional postprocessing step
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # Show 
      - name: Show Output BuildDate_DateRef
        run: echo ${{ steps.builddate.outputs.dateref }}
      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://portaldatransparencia.gov.br/download-de-dados/convenios/${{ steps.builddate.outputs.dateref }}
          downloaded_filename: data/convenios/zip/br_gov_portaldatransparencia_convenios_${{ steps.builddate.outputs.dateref }}.zip
          # postprocess: postprocess.ts
